---
language: php
services:
  - docker

before_install:
  - sudo pip install yamllint -qqq

script:
  - yamllint -c .lint.yml docker-compose.yml
  - docker-compose config --services

notifications:
  email: false

git:
quiet: true
